export const PROFILE = {
	name: 'Purple Pack',
	description: 'Welcome to Purple pack (African, Flavourful, Irresistible)',
};

export const NAVBAR_ITEMS = [
	{ name: 'ABOUT', href: '/about' },
	{ name: 'FAQ', href: '/faq' },
	{ name: 'KITCHEN', href: '/kitchen' },
];

export const MENU: FoodI[] = [
	{
		name: 'Egusi Soup',
		slug: 'egusi-soup',
		image: '/image2.JPG',
		hoverImage: '/image3.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 1000,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Jollof Rice',
		slug: 'jollof-rice',
		image: '/image3.JPG',
		hoverImage: '/image4.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 3000,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Olori Ofada',
		slug: 'olori-ofada',
		image: '/image4.JPG',
		hoverImage: '/image5.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ayamase Sauce',
		slug: 'ayamase-sauce',
		image: '/image5.JPG',
		hoverImage: '/image6.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 9,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Banga Soup',
		slug: 'banga-soup',
		image: '/image6.JPG',
		hoverImage: '/image7.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Efo Riro',
		slug: 'efo-riro',
		image: '/image7.JPG',
		hoverImage: '/image8.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 67352,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ogbona',
		slug: 'ogbona',
		image: '/image8.JPG',
		hoverImage: '/image9.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ewa Agoyin',
		slug: 'ewa-agoyin',
		image: '/image9.JPG',
		hoverImage: '/image10.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ifokore Ijebu',
		slug: 'ifokore-ijebu',
		image: '/image10.JPG',
		hoverImage: '/image11.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Asaro',
		slug: 'Asaro',
		image: '/image11.JPG',
		hoverImage: '/image12.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ila Alasepo',
		slug: 'ila-alasepo',
		image: '/image12.JPG',
		hoverImage: '/image13.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Buka Stew',
		slug: 'buka-stew',
		image: '/image13.JPG',
		hoverImage: '/image14.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
];

export const MENU_NEW: FoodI[] = [
	{
		name: 'Egusi Soup',
		slug: 'egusi-soup',
		image: '/image2.JPG',
		hoverImage: '/image3.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 1000,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Jollof Rice',
		slug: 'jollof-rice',
		image: '/image3.JPG',
		hoverImage: '/image4.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 3000,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Olori Ofada',
		slug: 'olori-ofada',
		image: '/image4.JPG',
		hoverImage: '/image5.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 10,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
	{
		name: 'Ayamase Sauce',
		slug: 'ayamase-sauce',
		image: '/image5.JPG',
		hoverImage: '/image6.JPG',
		description: `Dive into the rich and comforting flavors of Africa with our authentic Egusi Soup – a delicious blend of tradition and taste that captures the essence of the continent in every spoonful.`,
		ingredients: `Chicken, Sweet potato, Apple, Wild Rice, Goats cheese [Ingredients: Pasteurized goat's milk, salt, lactic starters, coagulant] (MILK), Yoghurt (MILK), Almonds (NUTS), Lemon Juice, Olive Oil, Balsamic Vinegar (SULPHITES), Mustard (MUSTARD), Honey, Garlic, Lemon Zest, Rapeseed oil, Thyme, Smoked Paprika, Salt, Black pepper, Mixed salad leaf`,
		price: 9,
		nutrition: [
			{ name: 'calories', value: '431kcal' },
			{ name: 'protein', value: '29.5g' },
			{ name: 'carbs', value: '44.6g' },
			{ name: 'fibre', value: '6.1g' },
			{ name: 'sugar', value: '12.4g' },
			{ name: 'fat', value: '15.6g' },
			{ name: 'saturated', value: '3.5g' },
			{ name: 'salt', value: '0.9g' },
		],
	},
];

export const HOW_IT_WORKS = [
	{
		step: 1,
		title: 'Browse through the kitchen.',
		description:
			'Discover our delectable menu online, filled with mouthwatering dishes prepared fresh in our kitchen.',
	},
	{
		step: 2,
		title: 'Find closest pickup store',
		description:
			'Locate the nearest pickup spot for your convenience from the available locations.',
	},
	{
		step: 3,
		title: 'Visit store, purchase and pickup ',
		description:
			'Visit our friendly store, make your order, and swiftly collect your delicious meal.',
	},
	{
		step: 4,
		title: 'Enjoy your meal',
		description:
			'Savor every bite of your flavorful meal from our restaurant – a culinary delight awaits!',
	},
];
export const KITCHENMENU: FoodP[] = [
	{
		name : 'BEEF AND ROMESCO SAUCE',
		slug : 'beef-and-romesco-sauce',
		image : '/image7.JPG',
		description : 'with roasted broccoli, roast vegetable quinoa and toasted almonds',
	},

]
